#!/bin/bash
set -e
set -x
if [ -z "$MYSQL_HOST" ]
then
  MYSQL_HOST=host.minikube.internal
else
  MYSQL_HOST=$MYSQL_HOST
fi
if [ -z "$MYSQL_PORT" ]
then
  MYSQL_PORT=3304
else
  MYSQL_PORT=$MYSQL_PORT
fi
if [ -z "$MYSQL_USER" ]
then
  MYSQL_USER=server
else
  MYSQL_USER=$MYSQL_USER
fi
if [ -z "$MYSQL_PASSWORD" ]
then
  MYSQL_PASSWORD=password
else
  MYSQL_PASSWORD=$MYSQL_PASSWORD
fi
if [ -z "$MYSQL_DATABASE" ]
then
  MYSQL_DATABASE=xrengine
else
  MYSQL_DATABASE=$MYSQL_DATABASE
fi
if [ -z "$VITE_CLIENT_HOST" ]
then
  VITE_CLIENT_HOST=local.theoverlay.io
else
  VITE_CLIENT_HOST=$VITE_CLIENT_HOST
fi
if [ -z "$VITE_SERVER_HOST" ]
then
  VITE_SERVER_HOST=api-local.theoverlay.io
else
  VITE_SERVER_HOST=$VITE_SERVER_HOST
fi
if [ -z "$VITE_MEDIATOR_SERVER" ]
then
  VITE_MEDIATOR_SERVER=https://authn.io
else
  VITE_MEDIATOR_SERVER=$VITE_MEDIATOR_SERVER
fi
if [ -z "$VITE_GAMESERVER_HOST" ]
then
  VITE_GAMESERVER_HOST=gameserver-local.theoverlay.io
else
  VITE_GAMESERVER_HOST=$VITE_GAMESERVER_HOST
fi

if [ -z "$VITE_APP_MAINNET_HOST_URL" ]
then
  VITE_APP_MAINNET_HOST_URL=gameserver-local.theoverlay.io
else
  VITE_APP_MAINNET_HOST_URL=$VITE_APP_MAINNET_HOST_URL
fi

if [ -z "$VITE_APP_VITE_APP_MAINNET_NFT_CANISTER_PRINCIPAL_ID" ]
then
  VITE_APP_VITE_APP_MAINNET_NFT_CANISTER_PRINCIPAL_ID=gameserver-local.theoverlay.io
else
  VITE_APP_VITE_APP_MAINNET_NFT_CANISTER_PRINCIPAL_ID=$VITE_APP_VITE_APP_MAINNET_NFT_CANISTER_PRINCIPAL_ID
fi

if [ -z "$VITE_APP_VITE_APP_MAINNET_NFT_CANISTER_ACCOUNT_ID" ]
then
  VITE_APP_VITE_APP_MAINNET_NFT_CANISTER_ACCOUNT_ID=gameserver-local.theoverlay.io
else
  VITE_APP_VITE_APP_MAINNET_NFT_CANISTER_ACCOUNT_ID=$VITE_APP_VITE_APP_MAINNET_NFT_CANISTER_ACCOUNT_ID
fi


if [ -z "$VITE_APP_MAINNET_USER_PRINCIPAL_ID" ]
then
  VITE_APP_MAINNET_USER_PRINCIPAL_ID=gameserver-local.theoverlay.io
else
  VITE_APP_MAINNET_USER_PRINCIPAL_ID=$VITE_APP_MAINNET_USER_PRINCIPAL_ID
fi

if [ -z "$VITE_APP_LOCAL_HOST_URL" ]
then
  VITE_APP_LOCAL_HOST_URL=gameserver-local.theoverlay.io
else
  VITE_APP_LOCAL_HOST_URL=$VITE_APP_LOCAL_HOST_URL
fi

if [ -z "$VITE_APP_LOCAL_NFT_CANISTER_PRINCIPAL_ID" ]
then
  VITE_APP_LOCAL_NFT_CANISTER_PRINCIPAL_ID=gameserver-local.theoverlay.io
else
  VITE_APP_LOCAL_NFT_CANISTER_PRINCIPAL_ID=$VITE_APP_LOCAL_NFT_CANISTER_PRINCIPAL_ID
fi

if [ -z "$VITE_APP_LOCAL_NFT_CANISTER_ACCOUNT_ID" ]
then
  VITE_APP_LOCAL_NFT_CANISTER_ACCOUNT_ID=gameserver-local.theoverlay.io
else
  VITE_APP_LOCAL_NFT_CANISTER_ACCOUNT_ID=$VITE_APP_LOCAL_NFT_CANISTER_ACCOUNT_ID
fi

if [ -z "$VITE_APP_LOCAL_USER_PRINCIPAL_ID" ]
then
  VITE_APP_LOCAL_USER_PRINCIPAL_ID=gameserver-local.theoverlay.io
else
  VITE_APP_LOCAL_USER_PRINCIPAL_ID=$VITE_APP_LOCAL_USER_PRINCIPAL_ID
fi

if [ -z "$VITE_APP_LOCAL_RPC_URL" ]
then
  VITE_APP_LOCAL_RPC_URL=gameserver-local.theoverlay.io
else
  VITE_APP_LOCAL_RPC_URL=$VITE_APP_LOCAL_RPC_URL
fi

if [ -z "$VITE_APP_TESTNET_RPC_URL" ]
then
  VITE_APP_TESTNET_RPC_URL=gameserver-local.theoverlay.io
else
  VITE_APP_TESTNET_RPC_URL=$VITE_APP_TESTNET_RPC_URL
fi

if [ -z "$VITE_APP_TESTNET_ACCOUNT_PRIVATE_KEY" ]
then
  VITE_APP_TESTNET_ACCOUNT_PRIVATE_KEY=gameserver-local.theoverlay.io
else
  VITE_APP_TESTNET_ACCOUNT_PRIVATE_KEY=$VITE_APP_TESTNET_ACCOUNT_PRIVATE_KEY
fi

if [ -z "$VITE_APP_MAINNET_RPC_URL" ]
then
  VITE_APP_MAINNET_RPC_URL=gameserver-local.theoverlay.io
else
  VITE_APP_MAINNET_RPC_URL=$VITE_APP_MAINNET_RPC_URL
fi

if [ -z "$VITE_APP_MAINNET_ACCOUNT_PRIVATE_KEY" ]
then
  VITE_APP_MAINNET_ACCOUNT_PRIVATE_KEY=gameserver-local.theoverlay.io
else
  VITE_APP_MAINNET_ACCOUNT_PRIVATE_KEY=$VITE_APP_MAINNET_ACCOUNT_PRIVATE_KEY
fi

if [ -z "$VITE_APP_MAINNET_WICP_CANISTER_PRINCIPAL_ID" ]
then
  VITE_APP_MAINNET_WICP_CANISTER_PRINCIPAL_ID=gameserver-local.theoverlay.io
else
  VITE_APP_MAINNET_WICP_CANISTER_PRINCIPAL_ID=$VITE_APP_MAINNET_WICP_CANISTER_PRINCIPAL_ID
fi

if [ -z "$VITE_APP_MAINNET_WICP_CANISTER_ACCOUNT_ID" ]
then
  VITE_APP_MAINNET_WICP_CANISTER_ACCOUNT_ID=gameserver-local.theoverlay.io
else
  VITE_APP_MAINNET_WICP_CANISTER_ACCOUNT_ID=$VITE_APP_MAINNET_WICP_CANISTER_ACCOUNT_ID
fi

if [ -z "$VITE_APP_MAINNET_BALL_COIN_CANISTER_PRINCIPAL_ID" ]
then
  VITE_APP_MAINNET_BALL_COIN_CANISTER_PRINCIPAL_ID=gameserver-local.theoverlay.io
else
  VITE_APP_MAINNET_BALL_COIN_CANISTER_PRINCIPAL_ID=$VITE_APP_MAINNET_BALL_COIN_CANISTER_PRINCIPAL_ID
fi

if [ -z "$VITE_APP_MAINNET_BALL_COIN_CANISTER_ACCOUNT_ID" ]
then
  VITE_APP_MAINNET_BALL_COIN_CANISTER_ACCOUNT_ID=gameserver-local.theoverlay.io
else
  VITE_APP_MAINNET_BALL_COIN_CANISTER_ACCOUNT_ID=$VITE_APP_MAINNET_BALL_COIN_CANISTER_ACCOUNT_ID
fi

if [ -z "$VITE_APP_LOCAL_WICP_CANISTER_PRINCIPAL_ID" ]
then
  VITE_APP_LOCAL_WICP_CANISTER_PRINCIPAL_ID=gameserver-local.theoverlay.io
else
  VITE_APP_LOCAL_WICP_CANISTER_PRINCIPAL_ID=$VITE_APP_LOCAL_WICP_CANISTER_PRINCIPAL_ID
fi

if [ -z "$VITE_APP_LOCAL_WICP_CANISTER_ACCOUNT_ID" ]
then
  VITE_APP_LOCAL_WICP_CANISTER_ACCOUNT_ID=gameserver-local.theoverlay.io
else
  VITE_APP_LOCAL_WICP_CANISTER_ACCOUNT_ID=$VITE_APP_LOCAL_WICP_CANISTER_ACCOUNT_ID
fi

if [ -z "$VITE_APP_LOCAL_BALL_COIN_CANISTER_PRINCIPAL_ID" ]
then
  VITE_APP_LOCAL_BALL_COIN_CANISTER_PRINCIPAL_ID=gameserver-local.theoverlay.io
else
  VITE_APP_LOCAL_BALL_COIN_CANISTER_PRINCIPAL_ID=$VITE_APP_LOCAL_BALL_COIN_CANISTER_PRINCIPAL_ID
fi

if [ -z "$VITE_APP_LOCAL_BALL_COIN_CANISTER_ACCOUNT_ID" ]
then
  VITE_APP_LOCAL_BALL_COIN_CANISTER_ACCOUNT_ID=gameserver-local.theoverlay.io
else
  VITE_APP_LOCAL_BALL_COIN_CANISTER_ACCOUNT_ID=$VITE_APP_LOCAL_BALL_COIN_CANISTER_ACCOUNT_ID
fi

if [ -z "$VITE_APP_MAINNET_SONIC_CANISTER_PRINCIPAL_ID" ]
then
  VITE_APP_MAINNET_SONIC_CANISTER_PRINCIPAL_ID=gameserver-local.theoverlay.io
else
  VITE_APP_MAINNET_SONIC_CANISTER_PRINCIPAL_ID=$VITE_APP_MAINNET_SONIC_CANISTER_PRINCIPAL_ID
fi

if [ -z "$VITE_APP_TESTNET_SONIC_CANISTER_PRINCIPAL_ID" ]
then
  VITE_APP_TESTNET_SONIC_CANISTER_PRINCIPAL_ID=gameserver-local.theoverlay.io
else
  VITE_APP_TESTNET_SONIC_CANISTER_PRINCIPAL_ID=$VITE_APP_TESTNET_SONIC_CANISTER_PRINCIPAL_ID
fi

if [ -z "$VITE_APP_LOCAL_USER_SEED_PHRASE" ]
then
  VITE_APP_LOCAL_USER_SEED_PHRASE="warrior polar domain allow type immense select only income swallow salt search"
else
  VITE_APP_LOCAL_USER_SEED_PHRASE="$VITE_APP_LOCAL_USER_SEED_PHRASE"
fi

if [ -z "$VITE_APP_MAINNET_USER_SEED_PHRASE" ]
then
  VITE_APP_MAINNET_USER_SEED_PHRASE="warrior polar domain allow type immense select only income swallow salt search"
else
  VITE_APP_MAINNET_USER_SEED_PHRASE="$VITE_APP_MAINNET_USER_SEED_PHRASE"
fi

if [ -z "$VITE_APP_GAME_JOIN_CHARGE_IN_PERCENTAGE" ]
then
  VITE_APP_GAME_JOIN_CHARGE_IN_PERCENTAGE=gameserver-local.theoverlay.io
else
  VITE_APP_GAME_JOIN_CHARGE_IN_PERCENTAGE="$VITE_APP_GAME_JOIN_CHARGE_IN_PERCENTAGE"
fi

if [ -z "$VITE_APP_MAINNET_PRIZE_POOL_ACCOUNT_PRINCIPAL_ID" ]
then
  VITE_APP_MAINNET_PRIZE_POOL_ACCOUNT_PRINCIPAL_ID=gameserver-local.theoverlay.io
else
  VITE_APP_MAINNET_PRIZE_POOL_ACCOUNT_PRINCIPAL_ID="$VITE_APP_MAINNET_PRIZE_POOL_ACCOUNT_PRINCIPAL_ID"
fi

if [ -z "$VITE_APP_MAINNET_PRIZE_POOL_ACCOUNT_SEED_PHRASE" ]
then
  VITE_APP_MAINNET_PRIZE_POOL_ACCOUNT_SEED_PHRASE="crime silly dolphin wash sponsor you weapon river increase tell number proud"
else
  VITE_APP_MAINNET_PRIZE_POOL_ACCOUNT_SEED_PHRASE="$VITE_APP_MAINNET_PRIZE_POOL_ACCOUNT_SEED_PHRASE"
fi

if [ -z "$VITE_APP_MAINNET_BOT_TEAM_ACCOUNT_PRINCIPAL_ID" ]
then
  VITE_APP_MAINNET_BOT_TEAM_ACCOUNT_PRINCIPAL_ID=gameserver-local.theoverlay.io
else
  VITE_APP_MAINNET_BOT_TEAM_ACCOUNT_PRINCIPAL_ID="$VITE_APP_MAINNET_BOT_TEAM_ACCOUNT_PRINCIPAL_ID"
fi

if [ -z "$VITE_APP_MAINNET_BOT_TEAM_ACCOUNT_SEED_PHRASE" ]
then
  VITE_APP_MAINNET_BOT_TEAM_ACCOUNT_SEED_PHRASE="coral hold school icon cover focus pink split market suggest fortune easy"
else
  VITE_APP_MAINNET_BOT_TEAM_ACCOUNT_SEED_PHRASE="$VITE_APP_MAINNET_BOT_TEAM_ACCOUNT_SEED_PHRASE"
fi

if [ -z "$VITE_APP_MAINNET_BALL_COIN_TRANSACTION_FEE" ]
then
  VITE_APP_MAINNET_BALL_COIN_TRANSACTION_FEE=gameserver-local.theoverlay.io
else
  VITE_APP_MAINNET_BALL_COIN_TRANSACTION_FEE="$VITE_APP_MAINNET_BALL_COIN_TRANSACTION_FEE"
fi

if [ -z "$VITE_APP_MAINNET_KYASSHU_HOST_URL" ]
then
  VITE_APP_MAINNET_KYASSHU_HOST_URL=gameserver-local.theoverlay.io
else
  VITE_APP_MAINNET_KYASSHU_HOST_URL="$VITE_APP_MAINNET_KYASSHU_HOST_URL"
fi

if [ -z "$VITE_APP_MAINNET_MARKETPLACE_CANISTER_PRINCIPAL_ID" ]
then
  VITE_APP_MAINNET_MARKETPLACE_CANISTER_PRINCIPAL_ID=gameserver-local.theoverlay.io
else
  VITE_APP_MAINNET_MARKETPLACE_CANISTER_PRINCIPAL_ID="$VITE_APP_MAINNET_MARKETPLACE_CANISTER_PRINCIPAL_ID"
fi

if [ -z "$VITE_APP_LOCAL_MARKETPLACE_CANISTER_PRINCIPAL_ID" ]
then
  VITE_APP_LOCAL_MARKETPLACE_CANISTER_PRINCIPAL_ID=gameserver-local.theoverlay.io
else
  VITE_APP_LOCAL_MARKETPLACE_CANISTER_PRINCIPAL_ID="$VITE_APP_LOCAL_MARKETPLACE_CANISTER_PRINCIPAL_ID"
fi

if [ -z "$VITE_APP_LOCAL_PRIZE_POOL_ACCOUNT_PRINCIPAL_ID" ]
then
  VITE_APP_LOCAL_PRIZE_POOL_ACCOUNT_PRINCIPAL_ID=gameserver-local.theoverlay.io
else
  VITE_APP_LOCAL_PRIZE_POOL_ACCOUNT_PRINCIPAL_ID="$VITE_APP_LOCAL_PRIZE_POOL_ACCOUNT_PRINCIPAL_ID"
fi

if [ -z "$VITE_APP_LOCAL_PRIZE_POOL_ACCOUNT_SEED_PHRASE" ]
then
  VITE_APP_LOCAL_PRIZE_POOL_ACCOUNT_SEED_PHRASE="crime silly dolphin wash sponsor you weapon river increase tell number proud"
else
  VITE_APP_LOCAL_PRIZE_POOL_ACCOUNT_SEED_PHRASE="$VITE_APP_LOCAL_PRIZE_POOL_ACCOUNT_SEED_PHRASE"
fi

if [ -z "$VITE_APP_LOCAL_BOT_TEAM_ACCOUNT_PRINCIPAL_ID" ]
then
  VITE_APP_LOCAL_BOT_TEAM_ACCOUNT_PRINCIPAL_ID=gameserver-local.theoverlay.io
else
  VITE_APP_LOCAL_BOT_TEAM_ACCOUNT_PRINCIPAL_ID="$VITE_APP_LOCAL_BOT_TEAM_ACCOUNT_PRINCIPAL_ID"
fi

if [ -z "$VITE_APP_LOCAL_BOT_TEAM_ACCOUNT_SEED_PHRASE" ]
then
  VITE_APP_LOCAL_BOT_TEAM_ACCOUNT_SEED_PHRASE="coral hold school icon cover focus pink split market suggest fortune easy"
else
  VITE_APP_LOCAL_BOT_TEAM_ACCOUNT_SEED_PHRASE="$VITE_APP_LOCAL_BOT_TEAM_ACCOUNT_SEED_PHRASE"
fi


if [ -z "$VITE_APP_LOCAL_BALL_COIN_TRANSACTION_FEE" ]
then
  VITE_APP_LOCAL_BALL_COIN_TRANSACTION_FEE=gameserver-local.theoverlay.io
else
  VITE_APP_LOCAL_BALL_COIN_TRANSACTION_FEE="$VITE_APP_LOCAL_BALL_COIN_TRANSACTION_FEE"
fi

if [ -z "$VITE_APP_KYASSHU_LOCAL_HOST_URL" ]
then
  VITE_APP_KYASSHU_LOCAL_HOST_URL=gameserver-local.theoverlay.io
else
  VITE_APP_KYASSHU_LOCAL_HOST_URL="$VITE_APP_KYASSHU_LOCAL_HOST_URL"
fi

if [ -z "$VITE_APP_IC_ENV" ]
then
  VITE_APP_IC_ENV=gameserver-local.theoverlay.io
else
  VITE_APP_IC_ENV="$VITE_APP_IC_ENV"
fi

if [ -z "$INSTANCESERVER_SHUTDOWN_DELAY_MS" ]
then
  INSTANCESERVER_SHUTDOWN_DELAY_MS=gameserver-local.theoverlay.io
else
  INSTANCESERVER_SHUTDOWN_DELAY_MS="$INSTANCESERVER_SHUTDOWN_DELAY_MS"
fi

docker start xrengine_minikube_db
eval $(minikube docker-env)

mkdir -p ./project-package-jsons/projects/default-project
cp packages/projects/default-project/package.json ./project-package-jsons/projects/default-project
find packages/projects/projects/ -name package.json -exec bash -c 'mkdir -p ./project-package-jsons/$(dirname $1) && cp $1 ./project-package-jsons/$(dirname $1)' - '{}' \;
DOCKER_BUILDKIT=1 docker build -t root-builder -f dockerfiles/package-root/Dockerfile-root .
DOCKER_BUILDKIT=1 docker build -t xrengine \
  --build-arg MYSQL_HOST=$MYSQL_HOST \
  --build-arg MYSQL_PORT=$MYSQL_PORT \
  --build-arg MYSQL_PASSWORD=$MYSQL_PASSWORD \
  --build-arg MYSQL_USER=$MYSQL_USER \
  --build-arg MYSQL_DATABASE=$MYSQL_DATABASE \
  --build-arg VITE_CLIENT_HOST=$VITE_CLIENT_HOST \
  --build-arg VITE_SERVER_HOST=$VITE_SERVER_HOST \
  --build-arg VITE_MEDIATOR_SERVER=$VITE_MEDIATOR_SERVER \
  --build-arg VITE_GAMESERVER_HOST=$VITE_GAMESERVER_HOST \
  --build-arg VITE_APP_MAINNET_HOST_URL=$VITE_APP_MAINNET_HOST_URL \
  --build-arg VITE_APP_MAINNET_NFT_CANISTER_PRINCIPAL_ID=$VITE_APP_MAINNET_NFT_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_MAINNET_NFT_CANISTER_ACCOUNT_ID=$VITE_APP_MAINNET_NFT_CANISTER_ACCOUNT_ID \
  --build-arg VITE_APP_MAINNET_USER_PRINCIPAL_ID=$VITE_APP_MAINNET_USER_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_HOST_URL=$VITE_APP_LOCAL_HOST_URL \
  --build-arg VITE_APP_LOCAL_NFT_CANISTER_PRINCIPAL_ID=$VITE_APP_LOCAL_NFT_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_NFT_CANISTER_ACCOUNT_ID=$VITE_APP_LOCAL_NFT_CANISTER_ACCOUNT_ID \
  --build-arg VITE_APP_LOCAL_USER_PRINCIPAL_ID=$VITE_APP_LOCAL_USER_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_RPC_URL=$VITE_APP_LOCAL_RPC_URL \
  --build-arg VITE_APP_TESTNET_RPC_URL=$VITE_APP_TESTNET_RPC_URL \
  --build-arg VITE_APP_TESTNET_ACCOUNT_PRIVATE_KEY=$VITE_APP_TESTNET_ACCOUNT_PRIVATE_KEY \
  --build-arg VITE_APP_MAINNET_RPC_URL=$VITE_APP_MAINNET_RPC_URL \
  --build-arg VITE_APP_MAINNET_ACCOUNT_PRIVATE_KEY=$VITE_APP_MAINNET_ACCOUNT_PRIVATE_KEY \
  --build-arg VITE_APP_MAINNET_WICP_CANISTER_PRINCIPAL_ID=$VITE_APP_MAINNET_WICP_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_MAINNET_WICP_CANISTER_ACCOUNT_ID=$VITE_APP_MAINNET_WICP_CANISTER_ACCOUNT_ID \
  --build-arg VITE_APP_MAINNET_BALL_COIN_CANISTER_PRINCIPAL_ID=$VITE_APP_MAINNET_BALL_COIN_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_MAINNET_BALL_COIN_CANISTER_ACCOUNT_ID=$VITE_APP_MAINNET_BALL_COIN_CANISTER_ACCOUNT_ID \
  --build-arg VITE_APP_LOCAL_WICP_CANISTER_PRINCIPAL_ID=$VITE_APP_LOCAL_WICP_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_WICP_CANISTER_ACCOUNT_ID=$VITE_APP_LOCAL_WICP_CANISTER_ACCOUNT_ID \
  --build-arg VITE_APP_LOCAL_BALL_COIN_CANISTER_PRINCIPAL_ID=$VITE_APP_LOCAL_BALL_COIN_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_BALL_COIN_CANISTER_ACCOUNT_ID=$VITE_APP_LOCAL_BALL_COIN_CANISTER_ACCOUNT_ID \
  --build-arg VITE_APP_MAINNET_SONIC_CANISTER_PRINCIPAL_ID=$VITE_APP_MAINNET_SONIC_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_TESTNET_SONIC_CANISTER_PRINCIPAL_ID=$VITE_APP_TESTNET_SONIC_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_USER_SEED_PHRASE="$VITE_APP_LOCAL_USER_SEED_PHRASE" \
  --build-arg VITE_APP_MAINNET_USER_SEED_PHRASE="$VITE_APP_MAINNET_USER_SEED_PHRASE" \
  --build-arg VITE_APP_GAME_JOIN_CHARGE_IN_PERCENTAGE=$VITE_APP_GAME_JOIN_CHARGE_IN_PERCENTAGE \
  --build-arg VITE_APP_MAINNET_PRIZE_POOL_ACCOUNT_PRINCIPAL_ID=$VITE_APP_MAINNET_PRIZE_POOL_ACCOUNT_PRINCIPAL_ID \
  --build-arg VITE_APP_MAINNET_PRIZE_POOL_ACCOUNT_SEED_PHRASE="$VITE_APP_MAINNET_PRIZE_POOL_ACCOUNT_SEED_PHRASE" \
  --build-arg VITE_APP_MAINNET_BOT_TEAM_ACCOUNT_PRINCIPAL_ID=$VITE_APP_MAINNET_BOT_TEAM_ACCOUNT_PRINCIPAL_ID \
  --build-arg VITE_APP_MAINNET_BOT_TEAM_ACCOUNT_SEED_PHRASE="$VITE_APP_MAINNET_BOT_TEAM_ACCOUNT_SEED_PHRASE" \
  --build-arg VITE_APP_MAINNET_BALL_COIN_TRANSACTION_FEE=$VITE_APP_MAINNET_BALL_COIN_TRANSACTION_FEE \
  --build-arg VITE_APP_MAINNET_KYASSHU_HOST_URL=$VITE_APP_MAINNET_KYASSHU_HOST_URL \
  --build-arg VITE_APP_MAINNET_MARKETPLACE_CANISTER_PRINCIPAL_ID=$VITE_APP_MAINNET_MARKETPLACE_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_MARKETPLACE_CANISTER_PRINCIPAL_ID=$VITE_APP_LOCAL_MARKETPLACE_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_PRIZE_POOL_ACCOUNT_PRINCIPAL_ID=$VITE_APP_LOCAL_PRIZE_POOL_ACCOUNT_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_PRIZE_POOL_ACCOUNT_SEED_PHRASE="$VITE_APP_LOCAL_PRIZE_POOL_ACCOUNT_SEED_PHRASE" \
  --build-arg VITE_APP_LOCAL_BOT_TEAM_ACCOUNT_PRINCIPAL_ID=$VITE_APP_LOCAL_BOT_TEAM_ACCOUNT_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_BOT_TEAM_ACCOUNT_SEED_PHRASE="$VITE_APP_LOCAL_BOT_TEAM_ACCOUNT_SEED_PHRASE" \
  --build-arg VITE_APP_LOCAL_BALL_COIN_TRANSACTION_FEE=$VITE_APP_LOCAL_BALL_COIN_TRANSACTION_FEE \
  --build-arg VITE_APP_KYASSHU_LOCAL_HOST_URL=$VITE_APP_KYASSHU_LOCAL_HOST_URL \
  --build-arg VITE_APP_IC_ENV=$VITE_APP_IC_ENV \
  --build-arg INSTANCESERVER_SHUTDOWN_DELAY_MS=$INSTANCESERVER_SHUTDOWN_DELAY_MS .
  
DOCKER_BUILDKIT=1 docker build -t xrengine-testbot -f ./dockerfiles/testbot/Dockerfile-testbot .