#!/bin/bash
set -e
set -x

STAGE=$1
LABEL=$2
PACKAGE=$3
START_TIME=$4
PRIVATE_ECR=$5
REGION=$6

DOCKER_BUILDKIT=1 docker build -t $LABEL-$PACKAGE -f dockerfiles/$PACKAGE/Dockerfile-$PACKAGE \
   --build-arg MYSQL_HOST=$MYSQL_HOST \
  --build-arg MYSQL_PORT=$MYSQL_PORT \
  --build-arg MYSQL_PASSWORD=$MYSQL_PASSWORD \
  --build-arg MYSQL_USER=$MYSQL_USER \
  --build-arg MYSQL_DATABASE=$MYSQL_DATABASE \
  --build-arg VITE_CLIENT_HOST=$VITE_CLIENT_HOST \
  --build-arg VITE_SERVER_HOST=$VITE_SERVER_HOST \
  --build-arg VITE_MEDIATOR_SERVER=$VITE_MEDIATOR_SERVER \
  --build-arg VITE_INSTANCESERVER_HOST=$VITE_INSTANCESERVER_HOST \
  --build-arg VITE_APP_MAINNET_HOST_URL=$VITE_APP_MAINNET_HOST_URL \
  --build-arg VITE_APP_MAINNET_NFT_CANISTER_PRINCIPAL_ID=$VITE_APP_MAINNET_NFT_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_MAINNET_NFT_CANISTER_ACCOUNT_ID=$VITE_APP_MAINNET_NFT_CANISTER_ACCOUNT_ID \
  --build-arg VITE_APP_MAINNET_USER_PRINCIPAL_ID=$VITE_APP_MAINNET_USER_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_HOST_URL=$VITE_APP_LOCAL_HOST_URL \
  --build-arg VITE_APP_LOCAL_NFT_CANISTER_PRINCIPAL_ID=$VITE_APP_LOCAL_NFT_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_NFT_CANISTER_ACCOUNT_ID=$VITE_APP_LOCAL_NFT_CANISTER_ACCOUNT_ID \
  --build-arg VITE_APP_LOCAL_USER_PRINCIPAL_ID=$VITE_APP_LOCAL_USER_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_RPC_URL=$VITE_APP_LOCAL_RPC_URL \
  --build-arg VITE_APP_TESTNET_RPC_URL=$VITE_APP_TESTNET_RPC_URL \
  --build-arg VITE_APP_TESTNET_ACCOUNT_PRIVATE_KEY=$VITE_APP_TESTNET_ACCOUNT_PRIVATE_KEY \
  --build-arg VITE_APP_MAINNET_RPC_URL=$VITE_APP_MAINNET_RPC_URL \
  --build-arg VITE_APP_MAINNET_ACCOUNT_PRIVATE_KEY=$VITE_APP_MAINNET_ACCOUNT_PRIVATE_KEY \
  --build-arg VITE_APP_MAINNET_WICP_CANISTER_PRINCIPAL_ID=$VITE_APP_MAINNET_WICP_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_MAINNET_WICP_CANISTER_ACCOUNT_ID=$VITE_APP_MAINNET_WICP_CANISTER_ACCOUNT_ID \
  --build-arg VITE_APP_MAINNET_BALL_COIN_CANISTER_PRINCIPAL_ID=$VITE_APP_MAINNET_BALL_COIN_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_MAINNET_BALL_COIN_CANISTER_ACCOUNT_ID=$VITE_APP_MAINNET_BALL_COIN_CANISTER_ACCOUNT_ID \
  --build-arg VITE_APP_LOCAL_WICP_CANISTER_PRINCIPAL_ID=$VITE_APP_LOCAL_WICP_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_WICP_CANISTER_ACCOUNT_ID=$VITE_APP_LOCAL_WICP_CANISTER_ACCOUNT_ID \
  --build-arg VITE_APP_LOCAL_BALL_COIN_CANISTER_PRINCIPAL_ID=$VITE_APP_LOCAL_BALL_COIN_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_BALL_COIN_CANISTER_ACCOUNT_ID=$VITE_APP_LOCAL_BALL_COIN_CANISTER_ACCOUNT_ID \
  --build-arg VITE_APP_MAINNET_SONIC_CANISTER_PRINCIPAL_ID=$VITE_APP_MAINNET_SONIC_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_TESTNET_SONIC_CANISTER_PRINCIPAL_ID=$VITE_APP_TESTNET_SONIC_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_USER_SEED_PHRASE="$VITE_APP_LOCAL_USER_SEED_PHRASE" \
  --build-arg VITE_APP_MAINNET_USER_SEED_PHRASE="$VITE_APP_MAINNET_USER_SEED_PHRASE" \
  --build-arg VITE_APP_GAME_JOIN_CHARGE_IN_PERCENTAGE=$VITE_APP_GAME_JOIN_CHARGE_IN_PERCENTAGE \
  --build-arg VITE_APP_MAINNET_PRIZE_POOL_ACCOUNT_PRINCIPAL_ID=$VITE_APP_MAINNET_PRIZE_POOL_ACCOUNT_PRINCIPAL_ID \
  --build-arg VITE_APP_MAINNET_PRIZE_POOL_ACCOUNT_SEED_PHRASE="$VITE_APP_MAINNET_PRIZE_POOL_ACCOUNT_SEED_PHRASE" \
  --build-arg VITE_APP_MAINNET_BOT_TEAM_ACCOUNT_PRINCIPAL_ID=$VITE_APP_MAINNET_BOT_TEAM_ACCOUNT_PRINCIPAL_ID \
  --build-arg VITE_APP_MAINNET_BOT_TEAM_ACCOUNT_SEED_PHRASE="$VITE_APP_MAINNET_BOT_TEAM_ACCOUNT_SEED_PHRASE" \
  --build-arg VITE_APP_MAINNET_BALL_COIN_TRANSACTION_FEE=$VITE_APP_MAINNET_BALL_COIN_TRANSACTION_FEE \
  --build-arg VITE_APP_MAINNET_KYASSHU_HOST_URL=$VITE_APP_MAINNET_KYASSHU_HOST_URL \
  --build-arg VITE_APP_MAINNET_MARKETPLACE_CANISTER_PRINCIPAL_ID=$VITE_APP_MAINNET_MARKETPLACE_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_MARKETPLACE_CANISTER_PRINCIPAL_ID=$VITE_APP_LOCAL_MARKETPLACE_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_PRIZE_POOL_ACCOUNT_PRINCIPAL_ID=$VITE_APP_LOCAL_PRIZE_POOL_ACCOUNT_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_PRIZE_POOL_ACCOUNT_SEED_PHRASE="$VITE_APP_LOCAL_PRIZE_POOL_ACCOUNT_SEED_PHRASE" \
  --build-arg VITE_APP_LOCAL_BOT_TEAM_ACCOUNT_PRINCIPAL_ID=$VITE_APP_LOCAL_BOT_TEAM_ACCOUNT_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_BOT_TEAM_ACCOUNT_SEED_PHRASE="$VITE_APP_LOCAL_BOT_TEAM_ACCOUNT_SEED_PHRASE" \
  --build-arg VITE_APP_LOCAL_BALL_COIN_TRANSACTION_FEE=$VITE_APP_LOCAL_BALL_COIN_TRANSACTION_FEE \
  --build-arg VITE_APP_KYASSHU_LOCAL_HOST_URL=$VITE_APP_KYASSHU_LOCAL_HOST_URL \
  --build-arg VITE_APP_IC_ENV=$VITE_APP_IC_ENV \
  --build-arg INSTANCESERVER_SHUTDOWN_DELAY_MS=$INSTANCESERVER_SHUTDOWN_DELAY_MS .
bash ./scripts/publish_ecr.sh $RELEASE_NAME ${TAG}__${START_TIME} $DOCKER_LABEL $PACKAGE $PRIVATE_ECR $AWS_REGION
